import React from "react";
import Head from "next/head";

import Header from "./Header";
import styled from "@emotion/styled";

type Props = {
	children: JSX.Element;
};

const LayoutContainer = styled.div`
	height: auto;
	.contents {
		width: 100%;
		max-width: 1140px;
		margin: 0 auto;
		padding: 40px 22px 0;
		display: flex;
	}
`;

export const Main = styled.main``;

const Layout = ({ children }: Props) => {
	return (
		<LayoutContainer>
			<Head>
				<title>Blog</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="contents">
				<Main>{children}</Main>
			</div>
		</LayoutContainer>
	);
};

export default Layout;
